#!/bin/bash

rm -rf target
doxygen Doxyfile
set PLANTUML_LIMIT_SIZE=8192
plantuml -charset UTF-8 -o "./target" *.puml
pandoc -f gfm ./Report.md -t docx -o ./target/ReportByPandoc.docx
zip -r target/SourceCode.zip ../../../ -x@SourceExclude.lst
